from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "alternate-background-color: rgb(0, 0, 0);")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setMaximumSize(QtCore.QSize(380, 16777215))
        self.main.setStyleSheet("#main {\n"
        "   border-left: 2px solid rgb(138, 138, 138);\n"
        "}\n"
        "Qwidget{\n"
        "    border-right: 2 px;\n"
        "    border-right-color: rgb(138, 138, 138);\n"
        "}\n"
        "QPushButton{\n"
        "   text-align: center;\n"
        "}\n"
        "")
        self.main.setObjectName("main")
        self.main_header = QtWidgets.QWidget(self.main)
        self.main_header.setGeometry(QtCore.QRect(0, 0, 381, 41))
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 100))
        self.main_header.setStyleSheet("#main_header {\n"
        "    border-bottom: 1px solid  rgb(138, 138, 138);\n"
        "    border-left: 2px solid  rgb(138, 138, 138);\n"
        "}")
        self.main_header.setObjectName("main_header")
        self.layoutWidget = QtWidgets.QWidget(self.main_header)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 314, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.column_headers = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.column_headers.setFont(font)
        self.column_headers.setStyleSheet("color: rgb(138, 138, 138);")
        self.column_headers.setObjectName("column_headers")
        self.horizontalLayout.addWidget(self.column_headers)
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.column_entries = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.column_entries.setFont(font)
        self.column_entries.setStyleSheet("color: rgb(138, 138, 138);")
        self.column_entries.setObjectName("column_entries")
        self.horizontalLayout.addWidget(self.column_entries)
        self.playground = QtWidgets.QFrame(self.main)
        self.playground.setGeometry(QtCore.QRect(10, 50, 371, 671))
        self.playground.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playground.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playground.setObjectName("playground")
        self.main_footer = QtWidgets.QWidget(self.main)
        self.main_footer.setGeometry(QtCore.QRect(0, 720, 381, 81))
        self.main_footer.setStyleSheet("#main_footer{\n"
        "   border-top: 1px solid rgb(138, 138, 138);\n"
        "    border-left: 2px solid  rgb(138, 138, 138);\n"
        "}")
        self.main_footer.setObjectName("main_footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.main_footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_column = QtWidgets.QPushButton(self.main_footer)
        self.add_column.setMinimumSize(QtCore.QSize(120, 35))
        self.add_column.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.add_column.setFont(font)
        self.add_column.setStyleSheet("\n"
        "QPushButton{\n"
        "   color: rgb(138, 138, 138);\n"
        "   background-color: transparent;\n"
        "   border-radius: 4px;\n"
        "   border: 2px solid rgb(5, 136, 71); \n"
        "}\n"
        "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_column.setIcon(icon1)
        self.add_column.setIconSize(QtCore.QSize(21, 21))
        self.add_column.setCheckable(True)
        self.add_column.setAutoDefault(False)
        self.add_column.setDefault(False)
        self.add_column.setFlat(False)
        self.add_column.setObjectName("add_column")
        self.horizontalLayout_3.addWidget(self.add_column)
        self.save_button = QtWidgets.QPushButton(self.main_footer)
        self.save_button.setMinimumSize(QtCore.QSize(120, 35))
        self.save_button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("QPushButton{\n"
        "  color: rgb(255, 255, 255);\n"
        "   background-color: rgb(0, 74, 0);\n"
        "   border-radius: 4px;\n"
        "   border: 2px solid rgb(5, 136, 71); \n"
        "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon2)
        self.save_button.setIconSize(QtCore.QSize(21, 21))
        self.save_button.setCheckable(True)
        self.save_button.setDefault(False)
        self.save_button.setFlat(False)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.playground.raise_()
        self.main_footer.raise_()
        self.main_header.raise_()
        self.gridLayout.addWidget(self.main, 0, 1, 1, 1)
        self.preview = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview.sizePolicy().hasHeightForWidth())
        self.preview.setSizePolicy(sizePolicy)
        self.preview.setStyleSheet("#preview {\n"
        "     border-left: 1px solid rgb(138, 138, 138);\n"
        "}\n"
        "")
        self.preview.setObjectName("preview")
        self.preview_header = QtWidgets.QWidget(self.preview)
        self.preview_header.setGeometry(QtCore.QRect(0, 0, 651, 41))
        self.preview_header.setMaximumSize(QtCore.QSize(16777215, 100))
        self.preview_header.setStyleSheet("#preview_header {\n"
        "    border-bottom: 1px solid rgb(138, 138, 138);\n"
        "    border-left: 1px solid rgb(138, 138, 138);\n"
        "}")
        self.preview_header.setObjectName("preview_header")
        self.column_entries_2 = QtWidgets.QLabel(self.preview_header)
        self.column_entries_2.setGeometry(QtCore.QRect(270, 10, 87, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.column_entries_2.setFont(font)
        self.column_entries_2.setStyleSheet("color: rgb(138, 138, 138);")
        self.column_entries_2.setObjectName("column_entries_2")
        self.preview_pane = QtWidgets.QWidget(self.preview)
        self.preview_pane.setGeometry(QtCore.QRect(10, 50, 641, 741))
        self.preview_pane.setObjectName("preview_pane")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.preview_pane)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.preview_pane.raise_()
        self.preview_header.raise_()
        self.gridLayout.addWidget(self.preview, 0, 2, 1, 1)
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMaximumSize(QtCore.QSize(160, 16777215))
        self.sidebar.setStyleSheet("QPushButton{\n"
        "   border:none;\n"
        "   text-align: left;\n"
        "   height 30px;\n""}")
        self.sidebar.setObjectName("sidebar")
        self.recent_forms_pane = QtWidgets.QWidget(self.sidebar)
        self.recent_forms_pane.setGeometry(QtCore.QRect(9, 259, 151, 461))
        self.recent_forms_pane.setStyleSheet("")
        self.recent_forms_pane.setObjectName("recent_forms_pane")
        self.sidebar_footer = QtWidgets.QWidget(self.sidebar)
        self.sidebar_footer.setGeometry(QtCore.QRect(0, 720, 161, 81))
        self.sidebar_footer.setStyleSheet("#sidebar_footer{\n"
        "   border-top: 1px solid rgb(138, 138, 138);\n"
        "}")
        self.sidebar_footer.setObjectName("sidebar_footer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar_footer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.theme_button = QtWidgets.QPushButton(self.sidebar_footer)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.theme_button.setFont(font)
        self.theme_button.setStyleSheet("QPushButton{\n"
        "   border:none;\n"
        "   text-align: centre;\n"
        "   height 30px;\n"
        "   color: rgb(138, 138, 138);\n""}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/sun-moon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.theme_button.setIcon(icon3)
        self.theme_button.setIconSize(QtCore.QSize(20, 20))
        self.theme_button.setCheckable(True)
        self.theme_button.setAutoExclusive(False)
        self.theme_button.setObjectName("theme_button")
        self.verticalLayout.addWidget(self.theme_button)
        self.widget = QtWidgets.QWidget(self.sidebar)
        self.widget.setGeometry(QtCore.QRect(-1, 200, 161, 61))
        self.widget.setStyleSheet("#widget{\n"
        "   border-top: 1px solid rgb(138, 138, 138);\n"
        "   border-bottom: 1px solid rgb(138, 138, 138);\n"
        "}")
        self.widget.setObjectName("widget")
        self.recent_forms = QtWidgets.QLabel(self.widget)
        self.recent_forms.setGeometry(QtCore.QRect(40, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.recent_forms.setFont(font)
        self.recent_forms.setStyleSheet("color: rgb(138, 138, 138);")
        self.recent_forms.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.recent_forms.setObjectName("recent_forms")
        self.form_icon = QtWidgets.QLabel(self.widget)
        self.form_icon.setGeometry(QtCore.QRect(20, 20, 18, 20))
        self.form_icon.setMinimumSize(QtCore.QSize(18, 20))
        self.form_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.form_icon.setText("")
        self.form_icon.setPixmap(QtGui.QPixmap(":/images/file-text.svg"))
        self.form_icon.setScaledContents(True)
        self.form_icon.setObjectName("form_icon")
        self.layoutWidget1 = QtWidgets.QWidget(self.sidebar)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 50, 141, 141))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Create_new_form_button = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Create_new_form_button.setFont(font)
        self.Create_new_form_button.setAutoFillBackground(False)
        self.Create_new_form_button.setStyleSheet("color: rgb(138, 138, 138);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Create_new_form_button.setIcon(icon4)
        self.Create_new_form_button.setIconSize(QtCore.QSize(20, 20))
        self.Create_new_form_button.setCheckable(True)
        self.Create_new_form_button.setAutoExclusive(True)
        self.Create_new_form_button.setObjectName("Create_new_form_button")
        self.verticalLayout_3.addWidget(self.Create_new_form_button)
        self.Open_files_button = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Open_files_button.setFont(font)
        self.Open_files_button.setStyleSheet("color: rgb(138, 138, 138);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/layers.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open_files_button.setIcon(icon5)
        self.Open_files_button.setIconSize(QtCore.QSize(20, 20))
        self.Open_files_button.setCheckable(True)
        self.Open_files_button.setAutoExclusive(True)
        self.Open_files_button.setObjectName("Open_files_button")
        self.verticalLayout_3.addWidget(self.Open_files_button)
        self.Open_files_button_2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Open_files_button_2.setFont(font)
        self.Open_files_button_2.setStyleSheet("color: rgb(138, 138, 138);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/folder (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open_files_button_2.setIcon(icon6)
        self.Open_files_button_2.setIconSize(QtCore.QSize(20, 20))
        self.Open_files_button_2.setCheckable(True)
        self.Open_files_button_2.setAutoExclusive(True)
        self.Open_files_button_2.setObjectName("Open_files_button_2")
        self.verticalLayout_3.addWidget(self.Open_files_button_2)
        self.Logo_header = QtWidgets.QWidget(self.sidebar)
        self.Logo_header.setGeometry(QtCore.QRect(0, 0, 161, 41))
        self.Logo_header.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Logo_header.setStyleSheet("#Logo_header {\n"
        "    border-bottom: 1px solid  rgb(138, 138, 138);\n"
        "}")
        self.Logo_header.setObjectName("Logo_header")
        self.recent_forms_2 = QtWidgets.QLabel(self.Logo_header)
        self.recent_forms_2.setGeometry(QtCore.QRect(30, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.recent_forms_2.setFont(font)
        self.recent_forms_2.setStyleSheet("color: rgb(138, 138, 138);")
        self.recent_forms_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.recent_forms_2.setWordWrap(True)
        self.recent_forms_2.setObjectName("recent_forms_2")
        self.form_icon_2 = QtWidgets.QLabel(self.Logo_header)
        self.form_icon_2.setGeometry(QtCore.QRect(10, 10, 18, 20))
        self.form_icon_2.setMinimumSize(QtCore.QSize(18, 20))
        self.form_icon_2.setMaximumSize(QtCore.QSize(18, 20))
        self.form_icon_2.setText("")
        self.form_icon_2.setPixmap(QtGui.QPixmap(":/images/logo.ico"))
        self.form_icon_2.setScaledContents(True)
        self.form_icon_2.setObjectName("form_icon_2")
        self.recent_forms_pane.raise_()
        self.widget.raise_()
        self.layoutWidget.raise_()
        self.sidebar_footer.raise_()
        self.Logo_header.raise_()
        self.gridLayout.addWidget(self.sidebar, 0, 0, 1, 1)
        self.preview.raise_()
        self.sidebar.raise_()
        self.main.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Excel Data Manager"))
        self.column_headers.setText(_translate("MainWindow", "Column Headers"))
        self.column_entries.setText(_translate("MainWindow", "Column Entries"))
        self.add_column.setText(_translate("MainWindow", "Edit Form"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.column_entries_2.setText(_translate("MainWindow", "Preview"))
        self.theme_button.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change Theme</p></body></html>"))
        self.theme_button.setText(_translate("MainWindow", "Theme"))
        self.recent_forms.setText(_translate("MainWindow", "Recent Forms"))
        self.Create_new_form_button.setText(_translate("MainWindow", "Create New Form"))
        self.Open_files_button.setText(_translate("MainWindow", "Generate Form"))
        self.Open_files_button_2.setText(_translate("MainWindow", " Open Form"))
        self.recent_forms_2.setText(_translate("MainWindow", "Data Entry Manager"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
